name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  typecheck:
    name: Typecheck
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: prisma:generate && yarn typecheck
      enable-sonar: true
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Building
    uses: sapphiredev/.github/.github/workflows/reusable-build.yml@main
